config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contact/new'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # verb          to: "controler#action"
  root              to: 'pages#home'
  get '/usluge',    to: 'pages#usluge'
  get '/cjenovnik', to: 'pages#cjenovnik'
  get '/kontakt',   to: 'pages#kontakt'
  get '/rezervacija', to: 'pages#rezervacija'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def usluge
  end

  def cjenovnik
  end

  def kontakt
  end

  def rezervacija
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= meta_title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= favicon_link_tag %>

    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>p ahmed</p>

app/views/pages/cjenovnik.html.erb
<div class="main_banner">
  <div class="container d-flex justify-content-center">
    <div class="section_usluge_text col-lg-6 col-sm-12" style="margin-top:50px;text-align: center;">
        <h1 class="text_section_header">Naš<br>Cjenovnik</h1>
        <hr>
        <p class="text_section_para">Ostati prvi naša je vizija, i put kojim smo odabrali kročiti kroz svaki radni dan i za svakog novog klijenta.</p>
        <a class="button_main button_main_div" href="/kontakt" style="margin-bottom: 100px;">Rezerviši svoj termin <i aria-hidden="true" class="fas fa-cut ml-3"></i></a>
    </div>
  </div>
</div>

<div class="container">

  <div class="section_usluge fixsec row align-items-center justify-content-center">
    <div class="section_usluge_cijene col-lg-12 col-sm-12">
      <ul class="tilesWrap">
        <li>
          <h2>13KM</h2>
          <h3>Šišanje</h3>
          <p>.................</p>
        </li>
        <li>
          <h2>18KM</h2>
          <h3>Šišanje i pranje kose</h3>
          <p>.................</p>
        </li>
        <li>
          <h2>16KM</h2>
          <h3>Šišanje i uređivanje brade</h3>
          <p>.................</p>
        </li>
        <li>
          <h2>22KM</h2>
          <h3>Šišanje, pranje kose i uređivanje brade</h3>
          <p>.................</p>
        </li>
        <li>
          <h2>5KM</h2>
          <h3>Uređivanje brade</h3>
          <p>.................</p>
        </li>
        <li>
          <h2>13KM</h2>
          <h3>Uređivanje i farbanje brade</h3>
          <p>.................</p>
        </li>
        <li>
          <h2>7KM</h2>
          <h3>Pranje i feniranje kose</h3>
          <p>.................</p>
        </li>
        <li>
          <h2>10KM</h2>
          <h3>Šišanje (Mašinicom i djeca)</h3>
          <p>.................</p>
        </li>
        <li>
          <h2>40KM</h2>
          <h3>Farbanje kose</h3>
          <p>.................</p>
        </li>
        <li>
          <h2>50KM</h2>
          <h3>Blajhanje kose</h3>
          <p>.................</p>
        </li>
        <li>
          <h2>40KM</h2>
          <h3>Pramenovi</h3>
          <p>.................</p>
        </li>
        <li>
          <h2>5KM</h2>
          <h3>Uklanjanje dlačica voskom</h3>
          <p>.................</p>
        </li>
      </ul>
    </div>
  </div>

  <div class="proizvodi row align-items-center">
    <div class="col-lg-6 col-md-6 col-sm-12">
      <div class="proizvodi_main_image"></div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12">
      <div class="line_home"> <%= image_tag "line.webp", :style => "width: 140px;margin-bottom: 20px;" %> </div>
      <h1 class="proizvodi_section_h">Dapper Dan <br>Matt Clay</h1>
      <p class="proizvodi_section_para">Strong Hold</p>
      <hr style="background-color: red; width: 50%; float: left;">
      <h3 class="proizvodi_section_cijena"><br>20KM</h3>
      <p class="proizvodi_section_desc">Dapper dan proizvod koji prkosi zakonima gravitacije. S malom količinom dobiti ćete puno. Mat efekt, čvrsto držanje, volumen i prirodni izgled. Ugodnog je mirisa i lako isperivo.</p>
      <ul>
        <li class="proizvodi_list"><i aria-hidden="true" class="fas fa-check check_icon"></i>Ugodan</li>
        <li class="proizvodi_list"><i aria-hidden="true" class="fas fa-check check_icon"></i>Cvrst</li>
        <li class="proizvodi_list"><i aria-hidden="true" class="fas fa-check check_icon"></i>Mat</li>
      </ul>
    </div>
  </div>

  <div class="proizvodi_topic">
    <h1 class="proizvodi_section_h" style="margin-top: 70px;">Ostali Proizvodi</h1>
    <hr class="topic_hr" style="background-color: red; width: 50%; margin-top:0px;">
    <p class="proizvodi_section_para"><br>S razlogom najbolji.</p>
  </div>

  <div class="proizvodi row justify-content-center">
    <div class="proizvodi_lines col-lg-4 col-md-6 col-sm-12">
      <div class="line_home"> <%= image_tag "detail4.webp", :style => "width: 120px;margin-bottom: 20px;" %> </div>
      <h1 class="proizvodi_section_h">GoodLook<br>Beard Oil</h1>
      <h3 class="proizvodi_section_cijena"><br>17.00 KM</h3>
      <hr style=" background-color: #1a2659;">
      <p class="proizvodi_section_desc">Ulje koje pomaže pri rastu brade.</p>
    </div>
    <div class="sec_image_white col-lg-4 col-md-6 col-sm-12">
      <div class="proizvodi_sec_image"></div>
    </div>
  </div>
  <div class="proizvodi p_zadnji row justify-content-center" style="margin-top: 70px;">
    <div class="sec_image_white col-lg-4 col-md-6 col-sm-12">
      <div class="proizvodi_sec_image_2"></div>
    </div>
    <div class="proizvodi_lines col-lg-4 col-md-6 col-sm-12">
      <div class="line_home"> <%= image_tag "detail2.webp", :style => "width: 120px;margin-bottom: 20px; margin-top:20px;" %> </div>
      <h1 class="proizvodi_section_h">GoodLook<br>Krema za lice i bradu</h1>
      <h3 class="proizvodi_section_cijena"><br>20.00 KM</h3>
      <hr style=" background-color: #1a2659;">
      <p class="proizvodi_section_desc" style="margin-bottom:30px;">Provjereni i pouzdani proizvođači iz naše ponude jamstvo su uredne, njegovane i lijepe kose.</p>
       <a class="button_main button_main_div" href="/kontakt" style="margin-bottom: 100px;">Naruči sada<i aria-hidden="true" class="fas fa-cut ml-3"></i></a>
    </div>
  </div>

</div>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/home.html.erb
<div class="container">
  <div class="hero">
    <div class="video_home">
      <div class="video_overlay">
        <%= video_tag "video123.mp4", playsinline: :playsinline, autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video" %>
      </div>
    </div>
    <div class="text_section">
      <div class="text_video">
        <div width="100px" height="100px"><%= image_tag "Homepic1.webp", :style => "width: 130px;margin-bottom: 20px;" %></div>
        <div class="line_home"> <%= image_tag "line.webp", :style => "width: 160px;margin-bottom: 20px;" %> </div>
        <h1 class="hero-header">GoodLook<br>Barber<br>Shop</h1>
        <p class="hero-para">Više od običnog frizera, nudimo vam klasične usluge sa legendarnim stilom.<br> Prva stranica na balkanu sa online rezervacijom.</p>
        <a class="button_main button_main_div" href="/rezervacija">Rezervacija <i aria-hidden="true" class="fas fa-cut ml-3"></i></a>
      </div>
    </div>
  </div>
  <div class="section_usluge row align-items-center">
    <div class="section_usluge_text col-lg-5 col-sm-12">
      <div class="line_home"> <%= image_tag "line.webp", :style => "width: 160px;margin-bottom: 20px;" %> </div>
        <h1 class="text_section_header">Najpopularnije<br>Usluge</h1>
        <hr>
        <p class="text_section_para">Više od običnog frizera, nudimo vam klasične usluge sa legendarnim stilom.</p>
        <a class="button_main button_main_div" href="/cjenovnik" style="margin-bottom: 100px;">Cjenovnik <i aria-hidden="true" class="fas fa-cut ml-3"></i></a>
    </div>
    <div class="section_usluge_cijene col-lg-7 col-sm-12">
      <ul class="tilesWrap">
        <li>
          <h2>13KM</h2>
          <h3>Šišanje kose</h3>
          <p>..................</p>
        </li>
        <li>
          <h2>18KM</h2>
          <h3>Šišanje i pranje kose</h3>
          <p>..................</p>
        </li>
        <li>
          <h2>5KM</h2>
          <h3>Uređivanje brade</h3>
          <p>..................</p>
        </li>
        <li>
          <h2>22KM</h2>
          <h3>Šišanje, pranje kose i uređivanje brade</h3>
          <p>..................</p>
        </li>
      </ul>
    </div>
  </div>

  <div class="banner_main">
    <div class="banner"></div>
    <div class="banner_text_over row">
      <div class="col-lg-6">
      <h1 class="text_header_banner">BarberShop<br>Sponzori i partneri</h1>
      <p class="text_section_banner">Sve je u stilu! I proizvodima.</p>
      <hr style="background-color: red;">
      </div>
      <div class="col-lg-6 d-flex align-items-center justify-content-around">
        <%= image_tag "DapperDan.webp", :style => "width: 90px;" %>
        <%= image_tag "sponzor1.webp", :style => "width: 100px;" %>
        <%= image_tag "sponzor2.webp", :style => "width: 100px;" %>
      </div>
    </div>
  </div>

  <main class="page-content">
    <div class="card">
      <div class="content">
        <h2 class="title">Sea Salt Spray</h2>
        <p class="copy">26KM</p>
        <button class="button_sec"><a href="/kontakt" style="text-decoration: none;color: white;">Buy Now</a></button>
      </div>
    </div>
    <div class="card">
      <div class="content">
        <h2 class="title">Fiber Wax</h2>
        <p class="copy">15 KM</p>
        <button class="button_sec"><a href="/kontakt" style="text-decoration: none;color: white;">Buy Now</a></button>
      </div>
    </div>
    <div class="card">
      <div class="content">
        <h2 class="title">Beard Oil</h2>
        <p class="copy">17 KM</p>
        <button class="button_sec"><a href="/kontakt" style="text-decoration: none;color: white;">Buy Now</a></button>
      </div>
    </div>
    <div class="card">
      <div class="content">

        <h2 class="title">Krema</h2>
        <p class="copy">20 KM</p>
        <button class="button_sec"><a href="/kontakt" style="text-decoration: none;color: white;">Buy Now</a></button>
      </div>
    </div>
  </main>

  <div class="d-flex justify-content-center">
   <div class="ponuda_tab" style="margin-bottom: 20px; padding-bottom: 30px;">
      <h1 class="ponuda_section_header">GoodLook</h1>
      <p class="ponuda_section_para">033 977-311 / Trg Heroja 31</p>
      <hr style="background-color: red; margin-bottom:27px;">
      <a class="button_main button_main_div" href="/rezervacija">Rezerviši svoj termin<i aria-hidden="true" class="fas fa-cut ml-3"></i></a>
    </div>
  </div>

  <div class="hero_footer d-flex align-items-end">
    <div class="container">
    <div class="overlay_hero"></div>
    <div class="slika_ponuda col-lg-6 col-sm-12 align-items-end">
      <div class="image_ponuda"><%= image_tag "50.webp", :style => " width: 100%; height:auto;filter: brightness( 109% ) contrast( 77% ) saturate( 89% ) hue-rotate(6deg); " %></div>
    </div>
  </div>

</div>

app/views/pages/kontakt.html.erb
<div class="main_ah" style="position: relative;">
  <div class="slider">
    <input type="radio" id="trigger2" name="slider" checked autofocus>
    <label for="trigger2"></label>
    <div class="slide bg2"><div class="sorta-block"><div data-text="31.00 KM"class="dashed-shadow sorta">31.00 KM</div></div></div>

    <input type="radio" id="trigger0" name="slider">
    <label for="trigger0"></label>
    <div class="slide bg0"><div class="sorta-block"><div data-text="31.00 KM"class="dashed-shadow sorta">31.00 KM</div></div></div>

    <input type="radio" id="trigger1" name="slider">
    <label for="trigger1"></label>
    <div class="slide bg1"><div class="sorta-block"><div data-text="31.00 KM"class="dashed-shadow sorta">31.00 KM</div></div></div>

    <input type="radio" id="trigger3" name="slider">
    <label for="trigger3"></label>
    <div class="slide bg3"><div class="sorta-block"><div data-text="31.00 KM"class="dashed-shadow sorta">31.00 KM</div></div></div>

    <input type="radio" id="trigger4" name="slider">
    <label for="trigger4"></label>
    <div class="slide bg4"><div class="sorta-block"><div data-text="31.00 KM"class="dashed-shadow sorta">31.00 KM</div></div></div>

    <input type="radio" id="trigger5" name="slider">
    <label for="trigger5"></label>
    <div class="slide bg5"><div class="sorta-block"><div data-text="26.00 KM"class="dashed-shadow sorta">26.00 KM</div></div></div>

    <input type="radio" id="trigger6" name="slider">
    <label for="trigger6"></label>
    <div class="slide bg6"><div class="sorta-block"><div data-text="31.00 KM"class="dashed-shadow sorta">31.00 KM</div></div></div>

    <input type="radio" id="trigger7" name="slider">
    <label for="trigger7"></label>
    <div class="slide bg7"><div class="sorta-block"><div data-text="26.00 KM"class="dashed-shadow sorta">26.00 KM</div></div></div>

    <input type="radio" id="trigger8" name="slider">
    <label for="trigger8"></label>
    <div class="slide bg8"><div class="sorta-block"><div data-text="20.00 KM"class="dashed-shadow sorta">20.00 KM</div></div></div>

     <input type="radio" id="trigger9" name="slider">
    <label for="trigger9"></label>
    <div class="slide bg9"><div class="sorta-block"><div data-text="27.80 KM"class="dashed-shadow sorta">27.80 KM</div></div></div>

    <input type="radio" id="trigger10" name="slider">
    <label for="trigger10"></label>
    <div class="slide bg10"><div class="sorta-block"><div data-text="28.80 KM"class="dashed-shadow sorta">28.80 KM</div></div></div>

    <input type="radio" id="trigger11" name="slider">
    <label for="trigger11"></label>
    <div class="slide bg11"><div class="sorta-block"><div data-text="32.00 KM"class="dashed-shadow sorta">32.00 KM</div></div></div>
  </div>
</div>

<div class="container" style="margin-top:30px;">
  <div class="kontakt row align-items-center justify-content-center">
    <div class="info col-lg-6 col-md-6 col-sm-12">
      <h1 class="proizvodi_section_h" style="text-transform:inherit; margin-top:15px;">Poručite produkte<br>ili nas kontaktirajte</h1>
      <hr class="kontakt_hr" style="background-color: red; width: 50%;">
      <p class="proizvodi_section_para"><br></p>
      <ul>
        <li class="proizvodi_list" style="text-transform:inherit;"><i aria-hidden="true" class="fas fa-check check_icon"></i>Poručite svoj željeni produkt</li>
        <li class="proizvodi_list" style="text-transform:inherit;"><i aria-hidden="true" class="fas fa-check check_icon"></i>I mi ćemo vam dostaviti u roku od par dana</li>
        <li class="proizvodi_list" style="text-transform:inherit;"><i aria-hidden="true" class="fas fa-check check_icon"></i>Ili nam možete poslati samo vaš upit putem E-Maila</li>
      </ul>
    </div>
    <div class="forma col-lg-6 col-md-6 col-sm-12">
          <h1 class="proizvodi_section_h" style="text-align: center; margin-top: 40px;">&bull; Kontakt &bull;</h1>
          <div class="underline"></div>
          <form action="https://formspree.io/f/xnqlnwpd" method="POST" id="contact_form">
            <div class="name">
              <label for="name"></label>
              <input type="text" placeholder="Ime:" name="name" id="name_input" required>
            </div>
            <div class="email">
              <label for="email"></label>
              <input type="email" placeholder="E-mail:" name="email" id="email_input" required>
            </div>
            <div class="telephone">
              <label for="name"></label>
              <input type="text" placeholder="Telefon:" name="telephone" id="telephone_input" required>
            </div>
            <div class="subject">
              <label for="subject"></label>
              <select placeholder="Subject line" name="subject" id="subject_input" optional>
                <option disabled hidden selected>Proizvod </option>
                <option style="color: black"><span class="grey_color">GoodLook Beard Oil 17.00 KM</span></option>
                <option style="color: black">GoodLook Krema 20.00 KM</option>
                <option style="color: black">DapperDan Matt Clay 31.00 KM</option>
                <option style="color: black">DapperDan Deluxe Pomade 31.00 KM</option>
                <option style="color: black">DapperDan Matt Paste 31.00 KM</option>
                <option style="color: black">DapperDan Heavy Hold Pomade 31.00 KM</option>
                <option style="color: black">DapperDan Ultra Matte Krema 31.00 KM</option>
                <option style="color: black">DapperDan Ultra Matte Puder 26.00 KM</option>
                <option style="color: black">DapperDan Grooming Tonic 31.00 KM</option>
                <option style="color: black">DapperDan Sea Salt 26.00 KM</option>
                <option style="color: black">DapperDan Vegetable Soap 20.00 KM</option>
                <option style="color: black">TIGI Manipulator 27.80 KM</option>
                <option style="color: black">TIGI Manipulator Matte 28.80 KM</option>
                <option style="color: black">TIGI Hair Stick 32.00 KM</option>
              </select>
            </div>
            <div class="telephone">
              <label for="name"></label>
              <input type="text" placeholder="Adresa" name="address" id="address_input" optional>
            </div>
            <div class="message">
              <label for="message"></label>
              <textarea name="message" placeholder="Vise informacija:" id="message_input" cols="30" rows="5" required></textarea>
            </div>
            <div class="submit" style="text-align:center; margin-top:12px">
              <input type="submit" class="button_main" value="Pošalji Poruku" style="text-align: center;" />
            </div>
          </form>
    </div>
  </div>

  <div class="mapa_info row align-items-center justify-content-center">
    <div class="info col-lg-6 col-md-6 col-sm-12">
      <div class="line_home"> <i class="fa fa-map mapaicon" aria-hidden="true"></i> </div>
      <h1 class="proizvodi_section_h">GoodLook<br>Barbershop</h1>
      <hr class="kontakt_hr" style="background-color: red; width: 50%;">
      <p class="proizvodi_section_para"><br>Trg Heroja 31, Sarajevo 71000</p>
      <ul>
        <li class="proizvodi_list" style="text-transform:inherit;"><i aria-hidden="true" class="fas fa-check check_icon"></i>goodlook.mails@gmail.com</li>
        <li class="proizvodi_list"><i aria-hidden="true" class="fas fa-check check_icon"></i>Pon-Pet 09:00 - 20:00 / Sub 09:00 - 18:00 / Ned - Zatvoreno</li>
        <li class="proizvodi_list"><i aria-hidden="true" class="fas fa-check check_icon"></i>033 977 311</li>
      </ul>
    </div>
    <div class="mapa col-lg-6 col-md-6 col-sm-12">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3684.677063521806!2d18.383199043654056!3d43.847903306185614!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4758c910ecfe32cd%3A0xbe553cd43bdc6657!2sGoodLook!5e0!3m2!1sbs!2sba!4v1617197308017!5m2!1sbs!2sba" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </div>
  </div>
</div>

app/views/pages/rezervacija.html.erb
<div class="main_banner" style="position: relative; z-index: -2;">
</div>
<div class="container"  style="margin-top: -250px;">
  <div class="proizvodi_topic" style="text-align: center;">
    <h1 class="proizvodi_section_h" style="margin-top: 70px; text-transform: none;">Online rezervacije</h1>
    <p class="proizvodi_section_para">Prvi u regionu sa online rezervacijama.</p>
    <hr style="background-color: red; width: 50%;">
    <p class="text_section_para">Izvršite svoju rezervaciju putem telefona 033 977 311 ili ONLINE.<br> A mi ćemo vam u kratkom vremenskom periodu preko emaila odobriti rezervaciju.<br> U svakom slučaju sigurni smo da ćete naći svoj termin!  </p>
  </div>

<!-- Calendly inline widget begin -->
<div class="calendly-inline-widget" data-url="https://calendly.com/goodlook-mails/sisanje?hide_event_type_details=1&hide_gdpr_banner=1&background_color=090e23&text_color=ffffff&primary_color=ffffff" style="min-width:320px;height:700px; margin-top: 20px;"></div>
<script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
<!-- Calendly inline widget end -->

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Radno Vrijeme</h3>
                        <ul>
                            <li>Pon–Petak: 09:00 – 20:00</li>
                            <li>Subota: 09:00 – 18:00</li>
                            <li>Nedelja: Zatvoreno</li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item text">
                        <h3>Kontakt</h3>
                        <p>Adresa: Trg heroja 31, Sarajevo 71000<br>
                          Bosna i Hercegovina<br>
                          Tel: 033 977 311</p>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>GoodLook</h3>
                        <p>Tim frizera u ulici Trg Heroja 31, u Sarajevu (Novo Sarajevo), nedaleko od tramvajske stanice Hrasno, blizu Željinog stadiona.</p>
                    </div>
                    <div class="col item social">
                      <ul class="social-icons">
                        <li><a class="facebook" target="_blank" href="https://www.facebook.com/goodlookbeautystudio"><i class="fab fa-facebook"></i></a></li>
                        <li><a class="twitter" target="_blank" href="https://www.instagram.com/goodlook_team/"><i class="fab fa-instagram"></i></a></li>
                        <li><a class="dribbble" target="_blank" href="mailto:goodlook.mails@gmail.com"><i class="far fa-envelope"></i></a></li>
                      </ul>
                    </div>
                </div>
                <div class="last_row row d-flex justify-content-space-between align-items-end">
                  <div class="col-lg-6">
                    <p class="copyright">GoodLook Barbershop © 2021</p>
                  </div>
                  <div class="footer_ahmed col-lg-6">
                          <div class="box">
                              <div class="title">
                                  <span class="block"></span>
                                  <a href="https://ahmedkucuk.herokuapp.com/" target="_blank" style="text-decoration: none;"><h1>Ahmed Kucuk<span></span></h1></a>
                              </div>
                              <div class="role">
                                  <div class="block"></div>
                                  <p>Fullstack Developer</p>
                              </div>
                          </div>
                      </div>
                </div>
            </div>
        </footer>
    </div>

app/views/shared/_navbar.html.erb
<header class="main-header">
    <div class="container">
      <nav class="navbar navbar-expand-lg main-nav px-0">
        <a class="navbar-brand" href="/" style="text-decoration: none;" hover="color:white;"> GOODLOOK </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="icon-bar icon-bar-1"></span>
          <span class="icon-bar icon-bar-2"></span>
          <span class="icon-bar icon-bar-3"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
          <ul class="navbar-nav ml-auto text-uppercase f1">
            <li>
              <%= link_to "Početna", root_path %>
            </li>
            <li>
              <%= link_to "Cjenovnik", cjenovnik_path %>
            </li>
            <li>
              <%= link_to "Tim i Galerija", usluge_path %>
            </li>
            <li>
              <%= link_to "Kontakt i Proizvodi", kontakt_path %>
            </li>
            <li class="lastLi">
              <%= link_to "Rezervacija", rezervacija_path %>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </header>

  <!--

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- Scripts -->
  <script src="scripts/index.js"></script>